baseURL = "https://neriman.me/"
theme = "hugo-bearcub"
copyright = "Nəriman (CC BY-SA 4.0)"
defaultContentLanguage = "en"

[markup]
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = false

[languages]
[languages.en]
title = "Neriman"
languageName = "English"
LanguageCode = "en"
contentDir = "content"
[languages.en.params]
madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
[languages.az]
title = "Nəriman"
languageName = "Azərbaycanca"
LanguageCode = "az"
contentDir = "content.az"
[languages.az.params]
madeWith = "[Bear Cub](https://github.com/clente/hugo-bearcub) ilə hazırlanıb"

[params]
title = "Nəriman"
dateFormat = "2006-01-02"
hideUntranslated = true
themeStyle = "original"

[markup.goldmark.renderer]
unsafe = true